version: "2"

services:
  imgshare:
    container_name: imgshare
    build:
      context: .
      dockerfile: Dockerfile
    image: imgshare:${DOCKER_IMAGE_TAG:-v1} # increment this number (or set the env value in your .env) to force portainer to rebuild the image https://github.com/portainer/portainer/issues/6288
    restart: always
    ports:
      - "${HOST_PORT}:${APP_PORT}" # Must be supplied by shell or in .env file
    env_file:
      - .env
    volumes:
      - "${HOST_DATA_PATH}:/workspace/prisma/data/" # Must be supplied by shell or in .env file
    user: node
